# Form implementation generated from reading ui file 'c:\Users\Лев\Desktop\programs\desktop_python\reminders_app\app\src\ui_files\task_widget.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_task_widget(object):
    def setupUi(self, task_widget):
        task_widget.setObjectName("task_widget")
        task_widget.resize(828, 75)
        task_widget.setMinimumSize(QtCore.QSize(828, 75))
        task_widget.setMaximumSize(QtCore.QSize(828, 75))
        task_widget.setMouseTracking(True)
        task_widget.setTabletTracking(True)
        task_widget.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        task_widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        task_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=task_widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 821, 73))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.widget_horizontal_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.widget_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.widget_horizontal_layout.setObjectName("widget_horizontal_layout")
        self.task_name_text_edit = QtWidgets.QPlainTextEdit(parent=self.horizontalLayoutWidget)
        self.task_name_text_edit.setMinimumSize(QtCore.QSize(731, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.task_name_text_edit.setFont(font)
        self.task_name_text_edit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.task_name_text_edit.setMouseTracking(True)
        self.task_name_text_edit.setTabletTracking(True)
        self.task_name_text_edit.setStyleSheet("text-align: center;")
        self.task_name_text_edit.setObjectName("task_name_text_edit")
        self.widget_horizontal_layout.addWidget(self.task_name_text_edit)
        self.task_date_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.task_date_label.setStyleSheet("")
        self.task_date_label.setObjectName("task_date_label")
        self.widget_horizontal_layout.addWidget(self.task_date_label)

        self.retranslateUi(task_widget)
        QtCore.QMetaObject.connectSlotsByName(task_widget)

    def retranslateUi(self, task_widget):
        _translate = QtCore.QCoreApplication.translate
        task_widget.setWindowTitle(_translate("task_widget", "Form"))
        self.task_date_label.setText(_translate("task_widget", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">01.01.2025</span></p></body></html>"))
